# Generated by Django 5.1.6 on 2025-02-22 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('contend', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_no', models.IntegerField()),
                ('mob', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('department', models.CharField(max_length=10)),
                ('designation', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ad_no', models.IntegerField()),
                ('mob', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('department', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteA.staff')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteA.student')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/assets/candidate/')),
                ('position', models.CharField(max_length=10)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteA.student')),
            ],
        ),
    ]
