# Generated by Django 5.1.6 on 2025-02-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0002_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(max_length=10),
        ),
    ]
