# Generated by Django 5.1.6 on 2025-02-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0005_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ad_no',
            field=models.IntegerField(null=True),
        ),
    ]
