# Generated by Django 5.1.6 on 2025-02-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0006_alter_student_ad_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mob',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mob',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
