# Generated by Django 5.1.6 on 2025-02-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0007_alter_staff_department_alter_staff_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='name',
        ),
    ]
