# Generated by Django 5.1.6 on 2025-02-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0008_remove_feed_email_remove_feed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
