# Generated by Django 5.1.6 on 2025-02-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0009_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='Student',
        ),
        migrations.AlterField(
            model_name='feed',
            name='Staff',
            field=models.IntegerField(),
        ),
    ]
