# Generated by Django 5.1.6 on 2025-02-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0010_remove_feed_student_alter_feed_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='Staff',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feedback',
            field=models.TextField(null=True),
        ),
    ]
