# Generated by Django 5.1.6 on 2025-02-28 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0011_alter_feed_staff_alter_feed_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='Staff',
        ),
        migrations.AddField(
            model_name='feed',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voteA.staff'),
            preserve_default=False,
        ),
    ]
