# Generated by Django 5.1.6 on 2025-02-28 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0012_remove_feed_staff_feed_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteA.staff')),
            ],
        ),
    ]
