# Generated by Django 5.1.6 on 2025-03-03 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0013_student_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AlterField(
            model_name='student_feed',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteA.student'),
        ),
    ]
