# Generated by Django 5.1.6 on 2025-03-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0014_remove_blog_category_alter_student_feed_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(null=True, upload_to='static/assets/blog/'),
        ),
    ]
