# Generated by Django 5.1.6 on 2025-03-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0015_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contend',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
