# Generated by Django 5.1.6 on 2025-03-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0016_alter_blog_contend_alter_blog_date_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
