# Generated by Django 5.1.6 on 2025-03-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0017_blog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(upload_to='static/assets/blog/'),
        ),
    ]
