# Generated by Django 5.1.6 on 2025-03-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0018_alter_blog_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=10, null=True)),
                ('img', models.ImageField(upload_to='static/assets/blog/')),
                ('date', models.DateField(null=True)),
                ('contend', models.TextField(null=True)),
            ],
        ),
    ]
