# Generated by Django 5.1.6 on 2025-03-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0019_blogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.AddField(
            model_name='student',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
