# Generated by Django 5.1.6 on 2025-03-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0020_delete_blogs_student_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
