# Generated by Django 5.1.6 on 2025-03-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0021_staff_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='type',
        ),
    ]
