# Generated by Django 5.1.6 on 2025-03-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0023_admin_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
