# Generated by Django 5.1.6 on 2025-03-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0024_staff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(upload_to='static/assets/'),
        ),
    ]
