# Generated by Django 5.1.6 on 2025-03-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0030_alter_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_feed',
            name='feedback',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
