# Generated by Django 5.1.6 on 2025-03-10 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0031_alter_student_feed_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voteA.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(upload_to='blog_img'),
        ),
    ]
