# Generated by Django 5.1.6 on 2025-03-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0032_blog_student_alter_blog_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
