# Generated by Django 5.1.6 on 2025-03-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0033_remove_blog_name_delete_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='img',
            field=models.ImageField(default=1, upload_to='student_img'),
            preserve_default=False,
        ),
    ]
