# Generated by Django 5.1.6 on 2025-03-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0034_staff_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='img',
            field=models.ImageField(upload_to='student_images'),
        ),
    ]
