# Generated by Django 5.1.6 on 2025-03-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0035_alter_staff_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='img',
        ),
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(default=1, upload_to='student_images'),
            preserve_default=False,
        ),
    ]
