# Generated by Django 5.1.6 on 2025-03-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0036_remove_staff_img_student_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(upload_to='student_image'),
        ),
    ]
