# Generated by Django 5.1.6 on 2025-03-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0038_alter_student_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(upload_to='blog_img/'),
        ),
    ]
