# Generated by Django 5.1.6 on 2025-03-11 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0039_alter_blog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(upload_to='student_images/'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='voteA.student')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_by', to='voteA.student')),
            ],
            options={
                'unique_together': {('student', 'candidate')},
            },
        ),
    ]
