# Generated by Django 5.1.6 on 2025-03-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0042_remove_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='votes',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
