# Generated by Django 5.1.3 on 2025-03-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0043_remove_student_votes_delete_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/'),
        ),
    ]
