# Generated by Django 5.2 on 2025-04-15 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0046_votingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('vote_count', models.IntegerField()),
                ('rank_in_dept', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteA.student')),
            ],
            options={
                'unique_together': {('candidate', 'department')},
            },
        ),
    ]
