# Generated by Django 5.2 on 2025-04-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteA', '0047_topcandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_hash', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
